# See for all values
# https://grafana.com/docs/tempo/latest/configuration/manifest/
# https://grafana.com/docs/tempo/latest/configuration

server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"

storage:
  trace:
    backend: local
    wal:
      path: /tmp/tempo/wal
    local:
      path: /tmp/tempo/blocks
