// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package models

import (
	"context"
)

const getTrue = `-- name: GetTrue :one
SELECT TRUE
`

func (q *Queries) GetTrue(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, getTrue)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
