apiVersion: 1

# Learn more about how to configure data sources
# See https://grafana.com/docs/grafana/latest/datasources/#built-in-core-data-sources
datasources:
  - name: Loki
    type: loki
    url: http://loki:3100
    access: proxy
    basicAuth: false

  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy

  - name: Tempo
    type: tempo
    url: http://tempo:3200
    access: proxy