// Code generated by "stringer -type=CodeType"; DO NOT EDIT.

package generate

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Usecase-1]
	_ = x[Request-2]
	_ = x[Command-3]
	_ = x[Query-4]
	_ = x[Job-5]
}

const _CodeType_name = "UnknownUsecaseRequestCommandQueryJob"

var _CodeType_index = [...]uint8{0, 7, 14, 21, 28, 33, 36}

func (i CodeType) String() string {
	if i < 0 || i >= CodeType(len(_CodeType_index)-1) {
		return "CodeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CodeType_name[_CodeType_index[i]:_CodeType_index[i+1]]
}
