// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package models

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ArrowerGueJobsWorkerPool struct {
	ID        string
	Queue     string
	Workers   int16
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
